### ISSUE TITLE
加上php8.3就好了，安装出问题

### ISSUE THREAD

**Issue by sixgodfan** [NotMings/open-oneinstack#1]
include/php-7.4.sh: line 94: pushd: php-7.4.33: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
include/php-7.4.sh: line 115: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: 'install' is up to date.
PHP install failed, Please Contact the author!
看了下src目录是有php-7.4.33.tar.gz的

**Comment by sixgodfan** [comment]
./install.sh --nginx_option 3 --php_option 9 --phpcache_option 1 --php_extensions imagick,fileinfo,redis,memcached --mphp_ver 82 --db_option 2 --dbinstallmethod 1 --dbrootpwd xxx --redis  --memcached  --ssh_port 22 --reboot

**Comment by NotMings** [comment]
> include/php-7.4.sh: line 94: pushd: php-7.4.33: No such file or directory make: *** No rule to make target 'clean'. Stop. include/php-7.4.sh: line 115: ./configure: No such file or directory make: *** No targets specified and no makefile found. Stop. make: 'install' is up to date. PHP install failed, Please Contact the author! 看了下src目录是有php-7.4.33.tar.gz的

请提供相应的操作系统等。。。而且你这个是安装的7.4吧

**Comment by sixgodfan** [comment]
Debian12 x64，按
[](https://github.com/NotMings/open-oneinstack/issues/1#issuecomment-1975092839
)
安装后不行才转安装php7.4的，后面也不行。你可以试试

**Comment by NotMings** [comment]
> Debian12 x64，按 安装后不行才转安装php7.4的，后面也不行。你可以试试

我自己试过是完全没问题的。在你提供的报错是找不到相应的文件，可以试试看是不是权限问题，或者网络连接问题导致没下载成功

**Comment by NotMings** [comment]
问题已修复
